added_allergies
OlSiv/python_byr_job pull request #21
Opened 2023-12-03 06:10 UTC by OlSiv

2023-12-03 10:14 UTC, burtovoy requested changes

2023-12-03 10:14 UTC, burtovoy commented on allergies/allergies.py
> +        list_res = Allergies(self.score).lst
Можно просто self.lst

2023-12-03 10:14 UTC, burtovoy commented on allergies/allergies.py
> +
пробелы в конце файла нужно убирать

2023-12-07 04:25 UTC, OlSiv commented on allergies/allergies.py
> +
Исправил

2023-12-07 04:30 UTC, OlSiv commented on allergies/allergies.py
> +        list_res = Allergies(self.score).lst
Исправил

2023-12-10 15:43 UTC, merged